
name: CI run unit tests 

on:
  workflow_dispatch:
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  run-unit-tests:

    runs-on: ubuntu-latest

    steps:
      - name: get code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: sbt
 
      - name: sbt for unit tests
        run: sbt -v +test

